### ISSUE TITLE
Incorporate errorcheck tool into our CI job (linter)

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#103]
It might be useful to incorporate the following tool into our CI job:
https://github.com/kisielk/errcheck

**Comment by JoseLSegura** [comment]
I was taking a look on this.

I run `errcheck ./...` on the repository root directory and I got a lot of errors (and 1 as exit value), but no explanation about what the problem is in each reported line.

For example, I got errors on almost **every** usage of `defer db.Close()`, but IDK why is `errcheck` reporting that

**Comment by tisnik** [comment]
IIRC the error value needs to be checked according the tool.

**Comment by JoseLSegura** [comment]
There is no error code in the output as far I can see, an example:

`storage/storage.go:186:18:      defer rows.Close()`

You can see line, column and content of the line.
The exit value of the program, from its README, can be 0 (no errors detected) or 1 if any error is detected

**Comment by tisnik** [comment]
I meant - `rows.Close()` returns an error value that is not checked, because we call it in `defer`. That's possibly what the tool detects.

**Comment by JoseLSegura** [comment]
Ok, now I understand and have a chance to trying to fix it :-D
