### ISSUE TITLE
Research: check whether pongo2 library can be used to templates used for current rules

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#137]
# Description

Currently descriptions and reasons for all rules are stored in separate repository. Each rule is stored in its own directory, and content is written as Markdown files with placeholders based on Jinja template engine.

We need to be able check which templating engine to use on Go side. Possible library can be
https://github.com/flosch/pongo2

# Task

1. Get access to current set of rules
1. Try to use **pongo2** library to apply templating
1. Check (just visually) if results are correct

# Acceptance criteria

1. The answer if we can use **pongo2** or not
1. List of issues that might be solved on rules side (like "do not use this...")

**Comment by Bee-lee** [comment]
So, I have some bad news. We probably can't use any Go templating engine for server-side rendering with the existing syntax of the markdown files with 'placeholders', let's call them **templates**.

The syntax of the templates is not Jinja and I quickly realized that the templates are definitely processed by JavaScript, because of JS-specific syntax in the templates, such as 

- `{{? pydata.package.indexOf('rh-mysql56') == 0 }}`

- `{{=node.allocatable_memory_gb.toFixed(2)}}`

and stuff like that. 

I tried finding a JS template engine that matches the syntax with the hopes of it being implemented in other languages too and the only one I found that uses syntax like `{{=...` is a popular **JS-only** engine [doT.js](http://olado.github.io/doT/), but I might be wrong about that. It's pretty cool and fast, but it's not implemented in other languages (for obvious reasons once you check out the [source code](https://github.com/olado/doT/blob/master/doT.js)).  
The only one I found that's implemented in a lot of languages is [Mustache](https://mustache.github.io/), but we obviously won't rewrite everything.  

There is some simple stuff which could easily be replaced by sed/awk/script, such as:
- `{{=pydata.version}}`

Even variable definitions during render time could be done thanks to the `{% with var=val %}` syntax:
- `{{const recommendedInstanceTypes = pydata.recommendations.unfit_tags[unfitTags][currentInstanceTypes];}}`

And then there's stuff that I **really** wouldn't like to rewrite...
- ```{{ for (var key in pydata.bc_memory_limit) {}}* The value of the parameter `resource.limits.memory` in the build config file `{{=key}}` is : **{{=pydata.bc_memory_limit[key][0]}}**
{{}}}```


I guess the conclusion for now is that we'll have to render it on client side/FE.
