### ISSUE TITLE
[Fuzz testing] PUT /clusters/000000000000000000000000000000000000/rules/0/like returns 500

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#385]
Response from the server:
```
{"status":"invalid cluster name format: '000000000000000000000000000000000000'"}
{"status":"Unable to get user id"}
```
This also applicable for:
PUT /clusters/000000000000000000000000000000000000/rules/0/dislike
PUT /clusters/000000000000000000000000000000000000/rules/0/reset_vote

**Comment by Sergey1011010** [comment]
May be fixed by https://github.com/RedHatInsights/insights-results-aggregator/pull/367 I changed some error status codes there to correct ones https://github.com/Sergey1011010/insights-results-aggregator/blob/cover-server-with-tests/server/router_utils.go#L97 and also fixed multiple json issue in some responses

**Comment by tisnik** [comment]
Well yes and no. I'm already having reproducers, these are as important as code fix :)
