### ISSUE TITLE
GET /organizations/2147483648/clusters returns 500

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#910]
Log excerpt:

```
{"level":"info","time":"2020-07-01T12:17:27Z","message":"Request received - URI: /api/insights-results-aggregator/v1/organizations/2147483648/clusters, Method: GET"}
{"level":"error","error":"pq: value \"2147483648\" is out of range for type integer","time":"2020-07-01T12:17:27Z","message":"Unable to get list of clusters"}
{"level":"error","error":"pq: value \"2147483648\" is out of range for type integer","time":"2020-07-01T12:17:27Z","message":"handleServerError"}
```

**Comment by joselsegura** [comment]
Apparently it is related to the upper limit of the ["integer" type in Postgresql](https://www.postgresql.org/docs/current/datatype-numeric.html).

Do we know the definition of the OrgID type? Depending on that, we can return a proper status code to this problem or maybe we need to use a bigger integer type for storing our fields in DB

**Comment by joselsegura** [comment]
The problem is now hidden after merging the PR [insights-results-smart-proxy#78](https://github.com/RedHatInsights/insights-results-smart-proxy/pull/78) the problem is not reproducible because the org id of the request doesn't match with the org id in the authentication credentials.

The problem is still there and probably we need to know how is organization id defined (how many bits are used for storing that integer) in order to implement some checks or modify the database field

**Comment by joselsegura** [comment]
This issue was closed because org id will continue be treated as an integer. The issue cannot be triggered anymore because the "org_id" in the request parameters will be matched with the org_id in the authentication token, so there is no possibility to try to query the database using a non valid organization id
